# Generated by Django 5.1.3 on 2024-11-19 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_enrollment_options_and_more'),
        ('students', '0002_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(help_text='Courses that the student is enrolled in.', through='courses.Enrollment', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(help_text='Date of birth of the student.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text='Unique email address of the student.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Full name of the student.', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(auto_now_add=True, help_text='Date when the student registered.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
