# Generated by Django 5.1.3 on 2024-11-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_courses_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
