# Generated by Django 5.1.3 on 2024-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2001-01-01', help_text='Date of birth of the student.'),
            preserve_default=False,
        ),
    ]
