# Generated by Django 5.1.3 on 2024-11-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User ', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('username', 'email')},
        ),
    ]
